services:
  - type: web
    name: fgsm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_fgsm:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free